app/notificaciones/urls.py
from django.urls import path
from app.notificaciones import views

app_name = 'notificacion'

urlpatterns = [
    # Notificacion URLs
    path('notificaciones/', views.NotificacionesListView.as_view(), name="listarNotificaciones"),
]

app/productos/urls.py
from django.urls import path
from app.productos.views.producto import views
from app.productos.views.categoria import views as views_categoria
from app.productos.views.marca import views as views_marca
from app.productos.views.promocion import views as views_promocion

app_name = 'productos'

urlpatterns = [
    
    # Producto URLs
    path('crear/', views.ProductoCreateView.as_view(), name="crearProductos"),
    path('inventario/', views.ProductoListView.as_view(), name="listarProductos"),
    path('editar/<str:codigo_barra>/', views.ProductoUpdateView.as_view(), name="editarProductos"),
    path('delete/<str:codigo_barra>/', views.ProductoDeleteView.as_view(), name="eliminarProductos"),
    
    #Categorias URLs
    path('categorias/', views_categoria.CategoriaListView.as_view(), name="listarCategorias"),
    path('categorias/crear/', views_categoria.CategoriaCreateView.as_view(), name="crearCategorias"),
    path('categorias/editar/<int:pk>/', views_categoria.CategoriaUpdateView.as_view(), name="editarCategorias"),
    path('categorias/delete/<int:pk>/', views_categoria.CategoriaDeleteView.as_view(), name="eliminarCategorias"),
    #Marcas URLs
    path('marcas/', views_marca.MarcaListView.as_view(), name="listarMarcas"),
    path('marcas/crear/', views_marca.MarcaCreateView.as_view(), name="crearMarcas"),
    path('marcas/editar/<int:pk>/', views_marca.MarcaUpdateView.as_view(), name="editarMarcas"),
    path('marcas/delete/<int:pk>/', views_marca.MarcaDeleteView.as_view(), name="eliminarMarcas"),
    
    #Promocion
    path('promocion/', views_promocion.PromocionListView.as_view(), name="listarPromociones"),
    path('promocion/crear/', views_promocion.PromocionCreateView.as_view(), name="crearPromociones"),
    path('promocion/editar/<int:pk>/', views_promocion.PromocionUpdateView.as_view(), name="editarPromociones"),
    path('promocion/delete/<int:pk>/', views_promocion.PromocionDeleteView.as_view(), name="eliminarPromociones"),
    

]

app/users/urls.py
from django.urls import path
from app.users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.CustomRegisterView.as_view(), name="register"),
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path('logout/', views.CustomLogoutView.as_view(), name="logout"),
]

app/ventas/urls.py
from django.urls import path
from app.ventas.views.venta import views
from app.ventas.views.detalle_venta import views as views_detalle

app_name = 'ventas'

urlpatterns = [
    # Notificacion URLs
    path('venta/', views.VentaView.as_view(), name="crearVentas"),
    path('registro/', views.VentaListView.as_view(), name="listarVentas"),
    path('registro/delete/<int:pk>/', views.VentaDeleteView.as_view(), name="eliminarVentas"),
    
    # Detalle Ventas
    path('detalle/', views_detalle.DetalleListView.as_view(), name="listarDetalles"),
    
    #PDF 
    path('venta/<int:pk>/boleta/', views.PdfView.as_view(), name="pdf"),
]

kaufken/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('layout/', views.view_navbar),
    path('users/', include('app.users.urls')),
    path('productos/', include('app.productos.urls')),
    path('notificacion/', include('app.notificaciones.urls')),
    path('ventas/', include('app.ventas.urls')),
    path('reportes/', include('app.reportes.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/aside.html
<aside>
    <h2>Navegación</h2>
    <ul>
        {% if user.is_staff %}
        <li>
           <details class="details_inventario">
             <summary>>Opciones de Inventario 📦</summary>
             <ul>
                 <li><a href="{% url 'productos:listarProductos' %}">Inventario</a></li>
                 <li><a href="{% url 'productos:listarCategorias' %}">Tabla Categorias</a></li>
                 <li><a href="{% url 'productos:listarMarcas' %}">Tabla Marcas</a></li> 
             </ul>
           </details>
        </li>
        {% endif %}
        <li><a href="{% url 'ventas:crearVentas'%}">Registrar Venta 💰</a></li>
        <li><a href="{% url 'ventas:listarVentas'%}">Ventas 📊</a></li>
        <li><a href="{% url 'notificacion:listarNotificaciones' %}">Notificaciones 🔔</a></li>
        {% if user.is_superuser %}
            <li><a href="/admin/">Admin 🛠️</a></li>
        {% endif %}
        <li>
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout-button" aria-label="Logout Button" title="Cerrar Sesión">Cerrar Sesión 🚪</button>
            </form>
        </li>
    </ul>
</aside>

templates/partials/footer.html
<footer>
    <p>&copy; 2024 Panaderia Kaufken POS</p>
</footer>

templates/partials/header.html
<header>
    <a href="">
        <img class="logo" src="https://marketplace.canva.com/EAFu-jps5Is/1/0/1600w/canva-logo-panader%C3%ADa-pan-r%C3%BAstico-textura-vintage-marr%C3%B3n-beige-2_p5CbFh3fI.jpg" alt="">
    </a>
</header>