app/users/urls.py
from django.urls import path
from app.users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.CustomRegisterView.as_view(), name="register"),
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path('logout/', views.CustomLogoutView.as_view(), name="logout"),
]

kaufken/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('layout/', views.view_navbar),
    path('users/', include('app.users.urls')),
    path('productos/', include('app.productos.urls')),
    path('notificacion/', include('app.notificaciones.urls')),
    path('ventas/', include('app.ventas.urls')),
    path('reportes/', include('app.reportes.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

app/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Visitor(models.Model):
    target_user = models.OneToOneField(User, on_delete=models.CASCADE)
    session_key = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f"{self.target_user.username} - {self.session_key}"

app/users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.contrib.sessions.models import Session
from django.contrib.auth import login
from django.urls import reverse_lazy
from .models import Visitor

class CustomLoginView(LoginView):
    template_name = 'users/login.html'
    
    def form_valid(self, form):
        user = form.get_user()
        
        # Handle existing Visitor session
        if hasattr(user, 'visitor'):
            # Delete previous session if exists
            if Session.objects.filter(session_key=user.visitor.session_key).exists():
                Session.objects.get(session_key=user.visitor.session_key).delete()
            
            # Remove previous Visitor object
            user.visitor.delete()
        
        # Perform login
        response = super().form_valid(form)
        
        # Create new Visitor entry
        new_session_key = self.request.session.session_key
        Visitor.objects.create(target_user=user, session_key=new_session_key)
        
        return response

class CustomLogoutView(LogoutView):
    next_page = 'users:login'
    
    def dispatch(self, request, *args, **kwargs):
        # Delete Visitor entry if exists
        if hasattr(request.user, 'visitor'):
            request.user.visitor.delete()
        
        return super().dispatch(request, *args, **kwargs)

class CustomRegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('home')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()
        login(self.request, user)
        return response

app/users/templates/users/base_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Base Form</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static '/css/form.css' %}">
    {% block extra_head %}  <!-- Bloque para estilos adicionales -->
    {% endblock %}
</head>
<body>
    <header>
        <a href="{% url 'users:login' %}">
            Logo Empresa
        </a>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>&copy; 2024 Panaderia Kofken</p>
    </footer>
</body>
</html>
</html>

app/users/templates/users/base_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Base Form</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static '/css/login.css' %}">
    {% block extra_head %}  <!-- Bloque para estilos adicionales -->
    {% endblock %}
</head>
<body>
    <header>
        <a href="{% url 'users:login' %}">
            <img class="logo" src="https://marketplace.canva.com/EAFu-jps5Is/1/0/1600w/canva-logo-panader%C3%ADa-pan-r%C3%BAstico-textura-vintage-marr%C3%B3n-beige-2_p5CbFh3fI.jpg" alt="Logo">
        </a>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>&copy; 2024 Panaderia Kofken</p>
    </footer>
</body>
</html>

app/users/templates/users/login.html
{% extends "users/base_login.html" %}

{% load static %}

{% block title %}
    <title>Login</title>
{% endblock %}

{% block extra_head %}
{% endblock %}

{% block content %}
<form class="form-validation" action = "{% url 'users:login' %}" 
method = "post">
    {% csrf_token %}
    {{ form }}
    <button>Enviar</button>
</form>


{%  endblock %}

app/users/templates/users/register.html
{% extends "users/base_login.html" %}

{% load static %}

{% block title %}
    <title>Register</title>
{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block content %}
<form class="form-validation" action = "{% url 'users:register' %}" 
method = "post">
    {% csrf_token %}
    {{ form }}
    <button>Enviar</button>
</form>
{%  endblock %}