app/ventas/urls.py
from django.urls import path
from app.ventas.views.venta import views
from app.ventas.views.detalle_venta import views as views_detalle

app_name = 'ventas'

urlpatterns = [
    # Notificacion URLs
    path('venta/', views.VentaView.as_view(), name="crearVentas"),
    path('registro/', views.VentaListView.as_view(), name="listarVentas"),
    path('registro/delete/<int:pk>/', views.VentaDeleteView.as_view(), name="eliminarVentas"),
    
    # Detalle Ventas
    path('detalle/', views_detalle.DetalleListView.as_view(), name="listarDetalles"),
    
    #PDF 
    path('venta/<int:pk>/boleta/', views.PdfView.as_view(), name="pdf"),
]

kaufken/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('layout/', views.view_navbar),
    path('users/', include('app.users.urls')),
    path('productos/', include('app.productos.urls')),
    path('notificacion/', include('app.notificaciones.urls')),
    path('ventas/', include('app.ventas.urls')),
    path('reportes/', include('app.reportes.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/ventas/models.py
from django.db import models
from django.contrib.auth.models import User
from app.productos.models import Producto, Promocion
from decimal import Decimal
from django.forms.models import model_to_dict
from app.ventas.validation import *


class Venta(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    create_at = models.DateTimeField(auto_now_add=True)
    total = models.PositiveIntegerField(default=0)

    def calcular_total(self):
        # Calcula el total sumando los subtotales de los detalles
        self.total = sum(detalle.subtotal for detalle in self.detalles.all())
        self.save()
        
    def toJSON(self):
        item = model_to_dict(self)
        item['usuario_nombre'] = self.usuario.username if self.usuario else "Desconocida"
        item['create_at'] = self.create_at.strftime('%d-%m-%Y %H:%M')
        return item

    def delete(self, using=None, keep_parents=False):
        # Ajuste del stock de los productos antes de eliminar la venta
        for detalle in self.detalles.all():  # Usamos 'self.detalles.all()' que es más eficiente
            detalle.producto.stock += detalle.cantidad  # Aumentar el stock del producto
            detalle.producto.save()  # Guardamos el producto actualizado
        super(Venta, self).delete(using=using, keep_parents=keep_parents)  # Eliminamos la venta

    def clean(self):
        validate_venta(self)
    def __str__(self):
        return f"Venta {self.id} - Usuario: {self.usuario}"

    class Meta:
        db_table = 'venta'
        ordering = ['-create_at']
        

class Pago(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE, related_name='pagos')
    METODO_PAGOS = [
        ('EF', 'Efectivo'),
        ('TD', 'Tarjeta Débito'),
    ]
    metodo_pago = models.CharField(max_length=15, choices=METODO_PAGOS)
    monto = models.PositiveIntegerField()
    fecha_pago = models.DateTimeField(auto_now_add=True)
    es_pago_parcial = models.BooleanField(default=False)
    
    def toJSON(self):
        item = model_to_dict(self)
        item['fecha_pago'] = self.fecha_pago.strftime('%d-%m-%Y %H:%M')
        return item

    def __str__(self):
        return f"Pago {self.id} - Venta: {self.venta.id} - Monto: {self.monto}"
    
    def clean(self):
        validate_pago(self)

    class Meta:
        db_table = 'pago'


class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE, related_name='detalles')
    producto = models.ForeignKey(Producto, on_delete=models.SET_NULL, null=True)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    descuento_aplicado = models.PositiveIntegerField(default=0) # Descuento manual adicional
    promocion = models.ForeignKey(Promocion, on_delete=models.SET_NULL, null=True, blank=True)
    
    def save(self, *args, **kwargs):
        # Calcular el subtotal antes de guardar
        self.subtotal = Decimal(self.cantidad) * Decimal(self.precio_unitario)
        super().save(*args, **kwargs)
    def toJSON(self):
        item = model_to_dict(self)
        item['producto_nombre'] = self.producto.nombre if self.producto else "Desconocida"
        return item
    
    def clean(self):
        validate_detalle_venta(self) 
    def __str__(self):
        return f"Detalle {self.id} - Venta: {self.venta.id}"
    
    class Meta:
        db_table = 'detalle_venta'


class Caja(models.Model):
    nombre = models.CharField(max_length=130, unique=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    saldo_inicial = models.PositiveBigIntegerField(default=0)
    saldo_final = models.PositiveBigIntegerField(default=0)  # Cambiado a PositiveBigIntegerField para consistencia
    cerrado = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    close_at = models.DateTimeField(null=True, blank=True)  # Permite nulos si no está cerrada aún

    class Meta:
        db_table = 'caja'
        ordering = ['-created_at']

    def __str__(self):
        return f"Caja {self.nombre} - {self.created_at}"


class ArqueoCaja(models.Model):
    caja = models.ForeignKey(Caja, on_delete=models.CASCADE, related_name='arqueos')
    monto_inicial = models.PositiveIntegerField()
    monto_real = models.PositiveIntegerField()
    fecha_arqueo = models.DateTimeField()
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    @property
    def diferencia(self):
        return self.monto_real - self.monto_inicial

    class Meta:
        db_table = 'arqueo_caja'

    def __str__(self):
        return f"Arqueo {self.id} - Caja: {self.caja.nombre}"

app/ventas/forms.py
from django import forms
from app.ventas.models import Venta, DetalleVenta, Pago
from app.productos.models import Producto
from django.forms import ModelChoiceField, Select
from django.utils.timezone import localtime

class VentaForm(forms.ModelForm):
    total = forms.IntegerField(
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'readonly': 'readonly',  
        }),
        label='Total de la Venta',
    )

    class Meta:
        model = Venta
        fields = ['total']  # Eliminamos metodo_pago ya que ahora está en Pago

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:  # Si la instancia ya existe
            self.fields['total'].initial = self.instance.total


class PagoForm(forms.ModelForm):
    class Meta:
        model = Pago
        fields = ['metodo_pago', 'monto']
        widgets = {
            'metodo_pago': forms.Select(attrs={'class': 'form-control'}),
            'monto': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Monto del pago'}),
        }
        labels = {
            'metodo_pago': 'Método de Pago',
            'monto': 'Monto',
        }

    def clean_monto(self):
        monto = self.cleaned_data.get('monto')
        if monto is not None:
            if monto <= 0:
                raise forms.ValidationError("El monto debe ser un número entero positivo.")
            if monto != int(monto):  # Verifica que sea un entero
                raise forms.ValidationError("El monto debe ser un número entero.")
        return monto


class DetalleVentaForm(forms.ModelForm):
    search = ModelChoiceField(
        queryset=Producto.objects.none(),
        widget=Select(attrs={
            'class': 'form-control select2',
            'placeholder': 'Buscar Producto...',
        })     
    )

    class Meta:
        model = DetalleVenta
        fields = ['producto', 'cantidad', 'precio_unitario']
        widgets = {
            'producto': forms.Select(attrs={'class': 'form-control select2'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Cantidad'}),
            'precio_unitario': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Precio unitario'}),
        }
        labels = {
            'producto': 'Producto',
            'cantidad': 'Cantidad',
            'precio_unitario': 'Precio Unitario',
        }

app/reportes/views/venta/views.py
from typing import Any
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from app.reportes.forms import ReportForm
# Create your views here.
class reportVentaView(TemplateView):
    template_name = 'report_venta.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Reporte de Ventas'
        context['entity'] = "Reportes"
        context['list_url'] = reverse_lazy('reportes:reporteVenta')
        context['form'] = ReportForm()
        return context

app/ventas/views/detalle_venta/views.py

from django.urls import reverse_lazy
from django.http import JsonResponse
from app.ventas.models import DetalleVenta
from django.views.generic import CreateView, ListView, DeleteView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from kaufken.mixin import StaffMemberRequiredMixin


class DetalleListView(LoginRequiredMixin, StaffMemberRequiredMixin, ListView):
    model = DetalleVenta
    template_name = "detalle_venta/table.html"
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Registros de Detalles Ventas'
        context['entity'] = 'Detalle Venta'
        context['create_url'] = reverse_lazy('ventas:crearVentas')
        return context

    def post(self, request, *args, **kwargs):
        data = {}
        action = request.POST['action']
        try:
            if action == 'search':
                data = []
                for i in DetalleVenta.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'No a ingresado ninguna accion'
        except Exception as error:
             data = {'error': str(error)}
        return JsonResponse(data, safe=False)

app/ventas/templates/venta/boleta.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="icon" type="image/png" href="{{ icon }}">
    <style>
        @page {
            width: 58mm;
            height: auto;
            margin: 0;
        }

        body {
            font-family: Arial, Helvetica, sans-serif;
            padding: 0;
            margin: 0;
            font-size: 7px; /* Tamaño de fuente ajustado */
            color: black;
            line-height: 0.5;
        }

        .container {
            width: 58mm;
            padding: 10px;
            margin: 0;
        }

        /* Cabecera */
        .header {
            text-align: center;
            margin-bottom: 10px;
        }

        .header-logo {
            width: 20px;
            height: 20px;
        }

        .header-info h1 {
            font-size: 9px;
            margin: 5px 0;
            text-transform: uppercase;
        }

        .header-info p {
            font-size: 6px;
            margin: 2px 0;
        }

        /* Información de la empresa */
        .empresa-info {
            text-align: center;
            margin-bottom: 10px;
        }

        .empresa-info p {
            font-size: 6px;
            margin: 2px 0;
        }

        /* Detalles de la venta */
        .details {
            margin-top: 10px;
        }

        .section-title {
            font-weight: bold;
            font-size: 7px;
            margin-bottom: 4px;
            text-transform: uppercase;
        }

        table {
            width: 100%;
            font-size: 6px;
            border-collapse: collapse;
            margin-bottom: 5px;
        }

        table th, table td {
            padding: 2px;
            text-align: left;
            border: 1px solid black;
        }

        table th {
            background-color: #f0f0f0;
            text-transform: uppercase;
        }

        .total {
            font-weight: bold;
            font-size: 7px;
            margin-top: 5px;
            text-align: right; /* Total alineado a la derecha */
        }

        /* Información del pago */
        .payment-info {
            margin-top: 10px;
        }

        .payment-info p {
            font-size: 6px;
            margin: 2px 0;
        }

        /* Pie de página */
        .footer {
            text-align: center;
            font-size: 5px;
            margin-top: 10px;
        }

        .footer p {
            margin: 0;
        }

        /* Alineación a la derecha */
        .venta {
            text-align: center;
        }

    </style>
</head>
<body>

<div class="container">
    <!-- Logo y encabezado -->
    <div class="header">
        <img src="{{ icon }}" alt="Logo" class="header-logo">
        <div class="header-info">
            <h1>{{ title }}</h1>
            <p><strong>Fecha:</strong> {{ venta.create_at|date:"d-m-Y H:i" }}</p>
            <p class="venta"><strong>Venta ID:</strong> {{ venta.id }}</p>
        </div>
    </div>

    <!-- Información de la empresa -->
    <div class="empresa-info">
        <p><strong>Nombre:</strong> {{ empresa.nombre }}</p>
        <p><strong>RUT:</strong> {{ empresa.rut }}</p>
        <p><strong>Dirección:</strong> {{ empresa.direccion }}</p>
        <p><strong>Email:</strong> {{ empresa.email }}</p>
    </div>

    <!-- Detalles de la venta -->
    <div class="details">
        <h2 class="section-title">Detalles Venta</h2>
        <table>
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Cant.</th>
                    <th>P. Unit.</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                {% for detalle in venta.detalles.all %}
                <tr>
                    <td>{{ detalle.producto.nombre }}</td>
                    <td>{{ detalle.cantidad }}</td>
                    <td>${{ detalle.precio_unitario}}</td>
                    <td class="text-right">${{ detalle.subtotal }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <p class="total"><strong>Total:</strong> ${{ venta.total}}</p>
    </div>

    <!-- Información de pagos -->
    <div class="payment-info">
        <h3 class="section-title">Pagos Realizados</h3>
        {% for pago in venta.pagos.all %}
        <p><strong>Pago:</strong> {{ pago.get_metodo_pago_display }}</p>
        <p><strong>Monto:</strong> ${{ pago.monto }}</p>
        <p><strong>Fecha:</strong> {{ pago.fecha_pago|date:"d-m-Y H:i" }}</p>
        <hr>
        {% endfor %}
    </div>

    <!-- Pie de página -->
    <div class="footer">
        <p>&copy; 2024 {{ empresa.nombre }} - Todos los derechos reservados.</p>
    </div>
</div>

</body>
</html>

app/ventas/templates/venta/table.html
{% extends "base_table.html" %}
{% load static %}
{%  block head_list %}
    <script src="{% static 'ventas/js/listar.js' %}"></script>
{% endblock %}


    {% block columns %}
        <th></th>
        <th>ID</th>
        <th>Usuario</th>
        <th>Fecha Venta</th>
        <th>Total</th>
    {% endblock columns %}

{% block rows %}
{% endblock rows %}

{% block javascript_list %}
{% endblock javascript_list %}

app/ventas/templates/venta/venta.html
{% extends "base_venta.html" %}
{% load static %}
{%  block head_list %}
    <script src="{% static 'ventas/js/select2.js' %}"></script>
    <link rel="stylesheet" href="{% static 'ventas/css/ventas.css' %}">

{% endblock %}

{% block form %}
<form class="venta_master" id="formRegistrarVenta" method="post" autocomplete="off" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="action" value="{{ action }}">
    <div class="detalle_venta">
        <div class="busqueda">
            {{ detalle_form.search }}
            <button class="limpiar_busqueda" type="button">
                <i class="fas fa-x"></i>
            </button>
        </div>
        <button id="eliminar_todo" class="d-none" type="button">
            <i class="fas fa-trash"></i>
            Eliminar todo los items
        </button>
        <table class="table" id="table">
            <thead>
                <tr>
                  <th>Acción</th>
                  <th>Producto</th>
                  <th>Categoría</th>
                  <th>Marca</th>
                  <th>Precio Unitario</th>
                  <th>Stock</th>
                  <th>Cantidad</th>
                  <th>Descuento</th>
                  <th>SubTotal</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div class="venta">
        <div class="detalle_pagos">
            {{ pago_form.metodo_pago.label_tag }}
            {{ pago_form.metodo_pago }}
            
            <div id="primer_pago" class="d-none">
                <h4>Primer Pago</h4>                
                {{ pago_form.monto.label_tag }}
                {{ pago_form.monto }}
                <span id="saldo-restante">Efectivo Restante: $0</span>
                <div id="vuelto" class="d-none">
                    <h4>Vuelto</h4>
                    <input id="vuelto-efectivo" min="0" type="number" readonly>
                </div>
            </div>

            <div id="segundo-pago" class="d-none">
                <h4>Segundo Pago</h4>
                <label for="metodo_pago_segundo">Método de Pago</label>
                <select name="metodo_pago_segundo" id="metodo_pago_segundo" class="form-control">
                    <option value="">Seleccione un método</option>
                    <option value="TD">Tarjeta Débito</option>
                </select>
                
                <label for="monto_segundo">Monto del Segundo Pago</label>
                <input type="number" name="monto_segundo" id="monto_segundo" class="form-control" placeholder="Monto del Segundo Pago" min="0" readonly>
                
                <button type="button" id="eliminar-segundo-pago" class="btn btn-danger mt-2">
                    Eliminar Segundo Pago
                </button>
            </div>
        </div>
        {{ venta_form.as_p }}

        <button type="submit" id = "button_formulario" class="button_formulario">
            <i class="fas fa-plus-circle"></i> {{ title }}
        </button>
    </div>
</form>
<link rel="stylesheet" href="{% static 'ventas/css/select2.css' %}">

{% endblock %}